export class LvlInfo {
  constructor(type, lvl, karma) {
    this.type = type.toLowerCase();
    this.lvl = lvl;
    this.karma = karma * 100;
  }

  isUser() { return this.type === "user"; }
  isModeration() { return this.type === "moderation"; }
  isAdmin() { return this.type === "admin"; }
}

export const levelTranslateNames = {
  LVL_APP_ACCESS: "lvl_app_access",
  LVL_CAN_CHANGE_PROFILE_IMAGE: "lvl_app_profile_image",
  LVL_CAN_CHANGE_STATUS: "lvl_app_status",
  LVL_CAN_MENTION: "lvl_app_mention",
  LVL_CAN_CHANGE_AVATAR_GIF: "lvl_avatar_gif",
  LVL_CAN_PIN_POST: "lvl_pin_post",
  LVL_CREATE_STICKERS: "lvl_create_stickers",
  LVL_MODERATOR_BLOCK: "lvl_moderate_block",
  LVL_MODERATOR_TO_DRAFTS: "lvl_moderate_to_drafts",
  LVL_MODERATOR_CHATS: "lvl_moderate_chats",
  LVL_MODERATOR_POST_TAGS: "lvl_moderate_post_tags",
  LVL_MODERATOR_FANDOM_IMAGE: "lvl_moderate_image_title",
  LVL_CAN_CHANGE_PROFILE_IMAGE_GIF: "lvl_app_profile_image_gif",
  LVL_MODERATOR_DESCRIPTION: "lvl_moderate_description",
  LVL_MODERATOR_NAMES: "lvl_moderate_names",
  LVL_MODERATOR_WIKI_EDIT: "lvl_wiki_edit",
  LVL_ANONYMOUS: "lvl_anonymous",
  LVL_MODERATOR_GALLERY: "lvl_moderate_gallery",
  LVL_MODERATOR_TRANSLATE: "lvl_translate",
  LVL_MODERATOR_LINKS: "lvl_moderate_links",
  LVL_MODERATOR_TAGS: "lvl_moderate_tags",
  LVL_MODERATOR_PIN_POST: "lvl_moderate_pin_post",
  LVL_MODERATOR_IMPORTANT: "lvl_moderate_important",
  LVL_MODERATOR_CLOSE_POST: "lvl_moderate_close_post",
  LVL_MODERATOR_RELAY_RACE: "lvl_moderate_relay_race",
  LVL_MODERATOR_RUBRIC: "lvl_moderate_rubrics",
  LVL_ADMIN_MODER: "lvl_admin_moder",
  LVL_ADMIN_FANDOM_NAME: "lvl_admin_fandom_rename",
  LVL_ADMIN_FANDOM_AVATAR: "lvl_admin_fandom_image",
  LVL_ADMIN_FANDOM_PARAMS: "lvl_admin_fandom_genres",
  LVL_ADMIN_FANDOM_CATEGORY: "lvl_admin_fandom_category",
  LVL_ADMIN_BAN: "lvl_ads_ban",
  LVL_ADMIN_POST_CHANGE_FANDOM: "lvl_post_fandom_change",
  LVL_ADMIN_FANDOMS_ACCEPT: "lvl_fandoms",
  LVL_ADMIN_USER_REMOVE_STATUS: "lvl_remove_status",
  LVL_ADMIN_USER_REMOVE_IMAGE: "lvl_remove_image",
  LVL_ADMIN_USER_REMOVE_NAME: "lvl_remove_name",
  LVL_ADMIN_USER_REMOVE_DESCRIPTION: "lvl_remove_descrpition",
  LVL_ADMIN_USER_REMOVE_LINK: "lvl_remove_link",
  LVL_ADMIN_USER_CHANGE_NAME: "lvl_change_user_name",
  LVL_ADMIN_USER_PUNISHMENTS_REMOVE: "lvl_user_punishment_remove",
  LVL_ADMIN_REMOVE_MODERATOR: "lvl_remove_moderator",
  LVL_ADMIN_MAKE_MODERATOR: "lvl_make_moderators",
  LVL_ADMIN_FANDOM_CLOSE: "lvl_fandom_close",
  LVL_ADMIN_TRANSLATE_MODERATOR: "lvl_translate_moderator",
  LVL_ADMIN_FANDOM_REMOVE: "lvl_remove_fandoms",
  LVL_ADMIN_FANDOM_VICEROY: "lvl_viceroy",
  LVL_ADMIN_FANDOM_ADMIN: "lvl_fandom_admin",
  LVL_ADMIN_FANDOM_EFFECTS: "lvl_accounts_effects",
  LVL_ADMIN_FANDOM_SET_COF: "lvl_fandom_set_cof",
  LVL_ADMIN_REMOVE_MEDIA: "lvl_fandom_remove_media",
  LVL_ADMIN_DEBUG_RECOUNT_LEVEL_AND_KARMA: "lvl_admin_recount",
  LVL_PROTOADMIN: "lvl_protoadmin",
};

const levels = {
  LVL_APP_ACCESS: new LvlInfo("User", 100, 0),
  LVL_CAN_CHANGE_PROFILE_IMAGE: new LvlInfo("User", 150, 0),
  LVL_CAN_CHANGE_STATUS: new LvlInfo("User", 175, 0),
  LVL_CAN_MENTION: new LvlInfo("User", 200, 0),
  LVL_CAN_CHANGE_AVATAR_GIF: new LvlInfo("User", 250, 0),
  LVL_CAN_PIN_POST: new LvlInfo("User", 260, 0),
  LVL_CREATE_STICKERS: new LvlInfo("User", 300, 0),
  //  Moderator
  LVL_MODERATOR_BLOCK: new LvlInfo("Moderation", 400, 300),
  LVL_MODERATOR_TO_DRAFTS: new LvlInfo("Moderation", 410, 320),
  LVL_MODERATOR_CHATS: new LvlInfo("Moderation", 415, 325),
  LVL_MODERATOR_POST_TAGS: new LvlInfo("Moderation", 420, 330),
  LVL_MODERATOR_FANDOM_IMAGE: new LvlInfo("Moderation", 425, 350),
  LVL_CAN_CHANGE_PROFILE_IMAGE_GIF: new LvlInfo("User", 450, 0),
  LVL_MODERATOR_DESCRIPTION: new LvlInfo("Moderation", 475, 400),
  LVL_MODERATOR_NAMES: new LvlInfo("Moderation", 490, 440),
  LVL_MODERATOR_WIKI_EDIT: new LvlInfo("Moderation", 500, 400),
  LVL_ANONYMOUS: new LvlInfo("User", 505, 0),
  LVL_MODERATOR_GALLERY: new LvlInfo("Moderation", 510, 450),
  LVL_MODERATOR_TRANSLATE: new LvlInfo("Admin", 515, 470),
  LVL_MODERATOR_LINKS: new LvlInfo("Moderation", 520, 475),
  LVL_MODERATOR_TAGS: new LvlInfo("Moderation", 530, 500),
  // LVL_MODERATOR_BACKGROUND_IMAGE: new LvlInfo("Moderation", 540, 540),
  LVL_MODERATOR_PIN_POST: new LvlInfo("Moderation", 560, 550),
  LVL_MODERATOR_IMPORTANT: new LvlInfo("Moderation", 575, 560),
  LVL_MODERATOR_CLOSE_POST: new LvlInfo("Moderation", 600, 650),
  LVL_MODERATOR_RELAY_RACE: new LvlInfo("Moderation", 620, 700),
  LVL_MODERATOR_RUBRIC: new LvlInfo("Moderation", 650, 800),
  //  Admin
  LVL_ADMIN_MODER: new LvlInfo("Admin", 700, 700),
  LVL_ADMIN_FANDOM_NAME: new LvlInfo("Admin", 725, 900),
  LVL_ADMIN_FANDOM_AVATAR: new LvlInfo("Admin", 730, 950),
  LVL_ADMIN_FANDOM_PARAMS: new LvlInfo("Admin", 750, 1000),
  LVL_ADMIN_FANDOM_CATEGORY: new LvlInfo("Admin", 790, 1080),
  LVL_ADMIN_BAN: new LvlInfo("Admin", 800, 1100),
  LVL_ADMIN_POST_CHANGE_FANDOM: new LvlInfo("Admin", 820, 1150),
  LVL_ADMIN_FANDOMS_ACCEPT: new LvlInfo("Admin", 850, 1200),
  LVL_ADMIN_USER_REMOVE_STATUS: new LvlInfo("Admin", 875, 1230),
  LVL_ADMIN_USER_REMOVE_IMAGE: new LvlInfo("Admin", 880, 1250),
  LVL_ADMIN_USER_REMOVE_NAME: new LvlInfo("Admin", 885, 1300),
  LVL_ADMIN_USER_REMOVE_DESCRIPTION: new LvlInfo("Admin", 888, 1350),
  LVL_ADMIN_USER_REMOVE_LINK: new LvlInfo("Admin", 890, 1400),
  LVL_ADMIN_USER_CHANGE_NAME: new LvlInfo("Admin", 895, 1410),
  LVL_ADMIN_USER_PUNISHMENTS_REMOVE: new LvlInfo("Admin", 900, 1420),
  LVL_ADMIN_REMOVE_MODERATOR: new LvlInfo("Admin", 910, 1450),
  LVL_ADMIN_MAKE_MODERATOR: new LvlInfo("Admin", 925, 1500),
  LVL_ADMIN_FANDOM_CLOSE: new LvlInfo("Admin", 940, 1550),
  LVL_ADMIN_TRANSLATE_MODERATOR: new LvlInfo("Admin", 945, 1600),
  LVL_ADMIN_FANDOM_REMOVE: new LvlInfo("Admin", 950, 1600),
  LVL_ADMIN_FANDOM_VICEROY: new LvlInfo("Admin", 980, 1650),
  LVL_ADMIN_FANDOM_ADMIN: new LvlInfo("Admin", 1000, 1700),
  LVL_ADMIN_FANDOM_EFFECTS: new LvlInfo("Admin", 1050, 1800),
  LVL_ADMIN_FANDOM_SET_COF: new LvlInfo("Admin", 1100, 2000),
  LVL_ADMIN_REMOVE_MEDIA: new LvlInfo("Admin", 1500, 2000),
  LVL_ADMIN_DEBUG_RECOUNT_LEVEL_AND_KARMA: new LvlInfo("Admin", 1200, 2100),
  //  Protoadmin
  LVL_PROTOADMIN: new LvlInfo("Admin", 5000, 100000),
};
export default levels;
